FROM gradle:jdk21-alpine
ARG PRODUCTION
ARG JDBC_DATABASE_PASSWORD
ARG JDBC_DATABASE_URL
ARG JDBC_DATABASE_USERNAME

ENV PRODUCTION ${PRODUCTION}
ENV JDBC_DATABASE_PASSWORD ${JDBC_DATABASE_PASSWORD}
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL}
ENV JDBC_DATABASE_USERNAME ${JDBC_DATABASE_USERNAME}

WORKDIR /app
EXPOSE 8080
COPY ./mcs-import-req-0.0.1-SNAPSHOT.jar /app
CMD ["java","-jar","mcs-import-req-0.0.1-SNAPSHOT.jar"]
#ENTRYPOINT ["java"]
#CMD ["-jar", "app.jar"]